env:
    browser: true
    es2021: true
extends: [standard-with-typescript, prettier]
parserOptions:
    ecmaVersion: latest
    sourceType: module
rules:
    {
        semi: ['error', 'always'],
        indent: ['error', 4],
        comma-dangle: ['error', 'never']
    }
